In [64]:
import pandas as pd 
import numpy as np 
from glob import glob
import matplotlib.pyplot as plt 

from utils.preprocess import Calibrator

%matplotlib inline

In [7]:
!ls data/processed/20190510/muscle/live
!ls data/processed/20190510/muscle/phantom

hwfm_1_1.png hwfm_1_3.png live_1_1.png live_1_2.png live_1_3.png
hwfm_1_2.png live_1_1.csv live_1_2.csv live_1_3.csv
hwfm_c.png    hwfm_k.png    phantom_e.csv phantom_i.csv phantom_n.csv
hwfm_e.png    hwfm_n.png    phantom_e.png phantom_i.png phantom_n.png
hwfm_h.png    phantom_c.csv phantom_h.csv phantom_k.csv
hwfm_i.png    phantom_c.png phantom_h.png phantom_k.png


In [67]:
phantom_measure = []
for p in "chik":
    path = "data/processed/20190510/muscle/phantom/phantom_{}.csv".format(p)
    phantom_measure += [pd.read_csv(path).values.T[1:]] # 波長不用取
phantom_measure = np.asarray(phantom_measure)

phantom_measure.shape

(4, 5, 36)

In [68]:
a = np.random.rand(5, 36)
b = np.random.rand(5, 36)

In [69]:
phantom_sim = phantom_measure * a + b

#### 每根SDS要各別fit！！
所以有5 * 36 = 180個參數...!!!

In [54]:
np.asarray([[[1,2,3,4],[10,20,30,40]], [[0, 0, 0, 0], [91, 92, 93, 94]]]).reshape(2, -1)

array([[ 1,  2,  3,  4, 10, 20, 30, 40],
       [ 0,  0,  0,  0, 91, 92, 93, 94]])

In [63]:
phantom_measure.reshape(4, -1).shape

(4, 180)

In [76]:
calib = Calibrator()
A, B, rr = calib.fit(phantom_measure.reshape(4, -1), phantom_sim.reshape(4, -1))
# A, B, rr = calib.fit(phantom_measure, phantom_sim)

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 40
         Function evaluations: 76
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 88
         Function evaluations: 164
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 32
         Function evaluations: 63
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 36
         Function evaluations: 70
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 37
         Function evaluations: 71
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 38
         Function evaluations: 72
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 37
         Function evaluations: 72
Optimization terminated successfu

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 42
         Function evaluations: 80
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 33
         Function evaluations: 63
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 39
         Function evaluations: 75
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 38
         Function evaluations: 72
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 39
         Function evaluations: 74
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 38
         Function evaluations: 75
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 36
         Function evaluations: 71
Optimization terminated successful

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 76
         Function evaluations: 135
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 47
         Function evaluations: 86
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 80
         Function evaluations: 151
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 43
         Function evaluations: 80
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 39
         Function evaluations: 74
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 42
         Function evaluations: 79
Optimization terminated successfully.
         Current function value: 0.000005
         Iterations: 25
         Function evaluations: 50
Optimization terminated successf

In [78]:
A.reshape(5, 36)

array([[0.69036385, 0.9206854 , 0.28632577, 0.52402041, 0.49794612,
        0.34156924, 0.48797654, 0.45688168, 0.80480095, 0.96687999,
        0.12559612, 0.10807649, 0.65208797, 0.82035588, 0.19861588,
        0.75456067, 0.73777212, 0.19795037, 0.23261099, 0.78523929,
        0.79507064, 0.61723482, 0.07959816, 0.77386347, 0.47764924,
        0.14317834, 0.41630228, 0.78322845, 0.80837704, 0.18493507,
        0.41386631, 0.16697318, 0.36927911, 0.07436433, 0.96216824,
        0.02211035],
       [0.95566096, 0.09950831, 0.31911262, 0.25863619, 0.80034867,
        0.47367673, 0.63669697, 0.74871376, 0.74962247, 0.44579173,
        0.4356091 , 0.38408604, 0.60032547, 0.51729032, 0.65209791,
        0.93367877, 0.35991385, 0.74124501, 0.536007  , 0.29243277,
        0.43911566, 0.65173331, 0.21501581, 0.31312527, 0.19862656,
        0.72049225, 0.05924972, 0.39256266, 0.33599054, 0.51943775,
        0.67372654, 0.60859538, 0.20213034, 0.59306256, 0.08995267,
        0.70537236],
      

In [72]:
a

array([[0.6900742 , 0.92068544, 0.28635447, 0.52387408, 0.49772779,
        0.34140269, 0.48798268, 0.45688169, 0.80480128, 0.9668244 ,
        0.12556249, 0.10806945, 0.6520569 , 0.82030195, 0.19852015,
        0.75443451, 0.73766116, 0.19778654, 0.23261725, 0.7852635 ,
        0.79507065, 0.61723481, 0.07947162, 0.77375021, 0.4775763 ,
        0.14312298, 0.41617385, 0.78328878, 0.80817192, 0.18446704,
        0.41364382, 0.16667889, 0.36908897, 0.07368659, 0.96202745,
        0.02094065],
       [0.95539441, 0.09934086, 0.3186218 , 0.25863617, 0.80014671,
        0.47363294, 0.63665843, 0.74866004, 0.74962248, 0.44569205,
        0.43560909, 0.38408603, 0.60021069, 0.51709758, 0.65208706,
        0.93364006, 0.35982519, 0.74124502, 0.5360279 , 0.2923403 ,
        0.43901259, 0.65175499, 0.21501582, 0.31293369, 0.19835141,
        0.72044793, 0.05911739, 0.39202337, 0.33580588, 0.51885735,
        0.6736967 , 0.60830912, 0.20117878, 0.59152455, 0.08848044,
        0.70402376],
      

#### 底下測試區

In [33]:
test = np.asarray([[[1, 2, 3], [4, 5, 6]],
           [[10, 20, 30], [40, 50, 60]],
           [[100, 200, 300], [400, 500, 600]
           ]])
test

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[ 10,  20,  30],
        [ 40,  50,  60]],

       [[100, 200, 300],
        [400, 500, 600]]])

In [31]:
test[:, :, 0].reshape(-1)

array([  1,   4,  10,  40, 100, 400])

In [42]:
# [波長數, 仿體數xSDS數]
test.transpose((2, 0, 1)).reshape(test.shape[2], -1)

array([[  1,   4,  10,  40, 100, 400],
       [  2,   5,  20,  50, 200, 500],
       [  3,   6,  30,  60, 300, 600]])

In [80]:
df = pd.read_csv("data/processed/20190510/muscle/phantom/phantom_c.csv")
df.iloc[:, 1:].values.T.shape

(5, 36)

In [87]:
df["0"]

0      479.615747
1     1221.902804
2     1508.062648
3     1777.987556
4     1978.196088
5     2379.334161
6     2582.056246
7     2895.736055
8     3177.175659
9     3246.679813
10    3741.266449
11    3901.874918
12    4027.717282
13    3970.366492
14    4318.978956
15    4539.179290
16    4470.516846
17    4163.928351
18    4500.705317
19    3761.639710
20    4181.737372
21    4082.357573
22    3319.717393
23    2987.911282
24    3290.369402
25    2332.721736
26    2200.300649
27    1946.586684
28    2274.648024
29    1477.382578
30    1610.704058
31    1360.706009
32     875.938907
33     784.320230
34     740.963175
35     640.927591
Name: 0, dtype: float64

In [82]:
d = df.iloc[:, 1:].values.T
np.asarray([d, d, d]).shape

(3, 5, 36)

In [83]:
{'a': 1} + {'b': 3}

TypeError: unsupported operand type(s) for +: 'dict' and 'dict'